### PR TITLE
Rails 3.2 is almost out

### PR DESCRIPTION
**Pull request by nicolasblanco**
Rails 3.2 is almost out

### CODE REVIEW

**Comment by lucascaton** [comment]
+1

**Comment by ipranay** [comment]
+1

**Comment by thinkinginmath** [comment]
+1

**Comment by PizzaPill** [comment]
+1

**Comment by straluna** [comment]
+1

**Comment by tzoro** [comment]
+1

**Comment by irohiroki** [comment]
+1

**Comment by AlessioRocco** [comment]
+1

**Comment by alansikora** [comment]
+1

**Comment by nicolasblanco** [comment]
i close this as it was fixed :)

**Comment by PizzaPill** [comment]
thank you!

**Pull request closed without merging**
