### PR TITLE
Activo theme

### PR DESCRIPTION
**Pull request by dmfrancisco**
I made a theme for your plugin and was hoping you could add it to the main repository.
Thanks for making this great project!

### CODE REVIEW

**Comment by gravityblast** [comment]
Just pulled! very nice theme, thank you!!

**Comment by dmfrancisco** [comment]
Thanks! Do you want me to add it to the gh-pages branch?

**Comment by weppos** [comment]
Activo was merged in 67f7e5ef72f96bb140c3db0dbded80aca06d1f03 but removed in ee47a1fa020705df4b828a3393801ff51a393437. I'm wondering if a new version, compatible with 0.6.2, is planned.

Thanks for your effort!

**Comment by dmfrancisco** [comment]
Yes, it still is compatible with 0.6.2. What happened was that activo became the default theme (with some minor changes) in the version 0.6.2, as you can see here: http://goo.gl/IrOk. So it's not activo.css anymore, but default.css. Thanks for the comment!

**Pull request closed without merging**
